version: '3.0'

services:
  app:
    image: cms:3.0
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/contacts
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=contacts
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root-password