version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts
    ports:
      - "3307:3306"
    networks:
      - networkmysql

  spring-app:
    build:
      context: .
      dockerfile: spring.Dockerfile
    container_name: cmscontainer
    depends_on:
      - mysql
    ports:
      - "8090:8080"
    networks:
      - networkmysql
    environment:
      MYSQL_HOST: mysqlcontainer
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: contacts
      MYSQL_USER: root
      MYSQL_PASSWORD: root

networks:
  networkmysql:
    driver: bridge
