version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    restart: unless-stopped
    networks:
      - networkmysql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  cms:
    build:
      context: .
      dockerfile: spring.Dockerfile
    image: cmsimage
    container_name: cmscontainer
    environment:
      MYSQL_HOST: mysqlcontainer
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${CMS_HOST_PORT}:8080"
    networks:
      - networkmysql
    depends_on:
      - mysql
    restart: unless-stopped

networks:
  networkmysql: