version: '3.8'
services:
  mysql:
    image: mysqlimage
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacts
    ports:
      - "3307:3306"
    networks:
      - networkmysql

  spring:
    build:
      context: .
      dockerfile: spring.Dockerfile
    image: springimage
    container_name: springcontainer
    depends_on:
      - mysql
    ports:
      - "8090:8080"
    networks:
      - networkmysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: contacts
      MYSQL_USER: root
      MYSQL_PASSWORD: root

networks:
  networkmysql:
    driver: bridge
